import { defineConfig } from 'vitepress'
import { fileURLToPath } from 'node:url'
import path from 'node:path'
import { templateCompilerOptions } from '@tresjs/core'
import typedocSidebar from '../api/typedoc-sidebar.json' with { type: 'json' }

/**
 * VitePress configuration for the `@cedric-pouilleux/stellar-hex` docs.
 *
 * - Guides: hand-written tutorials (Three.js basics, Vue integration).
 * - Examples: implementation snippets and live usage recipes.
 * - API:     auto-generated by TypeDoc + typedoc-vitepress-theme.
 */

const here = path.dirname(fileURLToPath(import.meta.url)) // docs/.vitepress
const root = path.resolve(here, '../..') // monorepo root

export default defineConfig({
  vue: { ...templateCompilerOptions },

  vite: {
    resolve: {
      alias: {
        '@cedric-pouilleux/stellar-hex/sim':  path.resolve(root, 'sim.ts'),
        '@cedric-pouilleux/stellar-hex/core': path.resolve(root, 'core.ts'),
        '@cedric-pouilleux/stellar-hex':      path.resolve(root, 'index.ts'),
      },
    },
  },

  title:       'Stellar Hex',
  description: 'Procedural celestial body generator — geometry, physics, simulation and rendering.',
  cleanUrls:   true,
  lastUpdated: true,
  base:        '/stellar-hex/',

  themeConfig: {
    nav: [
      { text: 'Guides',   link: '/guides/getting-started' },
      { text: 'Examples', link: '/examples/basic-planet/atmosphere' },
      { text: 'API',      link: '/api/' },
      {
        text: 'GitHub',
        link: 'https://github.com/cedric-pouilleux/stellar-hex',
      },
    ],

    sidebar: {
      '/guides/': [
        {
          text: 'Guides',
          items: [
            { text: 'Getting Started',  link: '/guides/getting-started'  },
            { text: 'Three.js Basics',  link: '/guides/threejs-basics'   },
            { text: 'Vue Integration',  link: '/guides/vue-integration'  },
            { text: 'Headless / Sim',   link: '/guides/headless-sim'     },
          ],
        },
      ],
      '/examples/': [
        {
          text: 'Examples',
          items: [
            {
              text: 'Body Types',
              items: [
                { text: 'Rocky planet',    link: '/examples/body-types/rocky'    },
                { text: 'Gas giant',       link: '/examples/body-types/gas'      },
                { text: 'Metallic planet', link: '/examples/body-types/metallic' },
                { text: 'Star',            link: '/examples/body-types/star'     },
              ],
            },
            {
              text: 'Basic Planet',
              items: [
                { text: 'With atmosphere', link: '/examples/basic-planet/atmosphere' },
                { text: 'With clouds',     link: '/examples/basic-planet/clouds'     },
              ],
            },
            {
              text: 'Gas Giant',
              items: [
                { text: 'With ring system', link: '/examples/gas-giant-rings/with-rings' },
              ],
            },
            {
              text: 'Star',
              items: [
                { text: 'With god-rays', link: '/examples/star-godrays/with-godrays' },
              ],
            },
            {
              text: 'Interactive Tiles',
              items: [
                { text: 'Hex tile viewer', link: '/examples/interactive-tiles/hex-viewer' },
              ],
            },
          ],
        },
      ],
      '/api/': [
        { text: 'Overview', link: '/api/' },
        ...typedocSidebar,
      ],
    },

    socialLinks: [
      { icon: 'github', link: 'https://github.com/cedric-pouilleux/stellar-hex' },
    ],

    search: { provider: 'local' },

    outline: { level: [2, 3] },

    footer: {
      message: 'Released under the license shown in the repo.',
      copyright: 'Copyright © Cedric Pouilleux',
    },
  },
})
