import { defineConfig } from 'vitepress'
import typedocSidebar from '../api/typedoc-sidebar.json' with { type: 'json' }

/**
 * VitePress configuration for the `@cedric-pouilleux/stellar-hex` docs.
 *
 * - Guides: hand-written tutorials (Three.js basics, Vue integration).
 * - Examples: implementation snippets and live usage recipes.
 * - API:     auto-generated by TypeDoc + typedoc-vitepress-theme.
 */
export default defineConfig({
  title:       'Stellar Hex',
  description: 'Procedural celestial body generator — geometry, physics, simulation and rendering.',
  cleanUrls:   true,
  lastUpdated: true,
  base:        '/stellar-hex/',

  themeConfig: {
    nav: [
      { text: 'Guides',   link: '/guides/getting-started' },
      { text: 'Examples', link: '/examples/basic-planet' },
      { text: 'API',      link: '/api/' },
      {
        text: 'GitHub',
        link: 'https://github.com/cedric-pouilleux/stellar-hex',
      },
    ],

    sidebar: {
      '/guides/': [
        {
          text: 'Guides',
          items: [
            { text: 'Getting Started',  link: '/guides/getting-started'  },
            { text: 'Three.js Basics',  link: '/guides/threejs-basics'   },
            { text: 'Vue Integration',  link: '/guides/vue-integration'  },
            { text: 'Headless / Sim',   link: '/guides/headless-sim'     },
          ],
        },
      ],
      '/examples/': [
        {
          text: 'Examples',
          items: [
            { text: 'Basic Planet',        link: '/examples/basic-planet'     },
            { text: 'Gas Giant with Rings',link: '/examples/gas-giant-rings'  },
            { text: 'Star with God-Rays',  link: '/examples/star-godrays'     },
            { text: 'Interactive Tiles',   link: '/examples/interactive-tiles'},
          ],
        },
      ],
      '/api/': [
        { text: 'Overview', link: '/api/' },
        ...typedocSidebar,
      ],
    },

    socialLinks: [
      { icon: 'github', link: 'https://github.com/cedric-pouilleux/stellar-hex' },
    ],

    search: { provider: 'local' },

    outline: { level: [2, 3] },

    footer: {
      message: 'Released under the license shown in the repo.',
      copyright: 'Copyright © Cedric Pouilleux',
    },
  },
})
