import { describe, it, expect } from 'vitest'
import { cloudCoverageFor, hasAtmosphere, auraParamsFor, atmosphereRadius } from './sceneBodyUtils'
import type { BodyConfig } from '../types/body.types'

// ── Helpers ───────────────────────────────────────────────────────

function rocky(overrides: Partial<BodyConfig> = {}): BodyConfig {
  return {
    name: 'Test',
    type: 'rocky',
    temperatureMin: -10,
    temperatureMax: 30,
    radius: 1,
    rotationSpeed: 0.05,
    axialTilt: 0,
    ...overrides,
  }
}

function star(overrides: Partial<BodyConfig> = {}): BodyConfig {
  return {
    name: 'Sun',
    type: 'star',
    spectralType: 'G',
    temperatureMin: 5000,
    temperatureMax: 15000,
    radius: 3,
    rotationSpeed: 0.02,
    axialTilt: 0,
    ...overrides,
  }
}

// ── atmosphereRadius ──────────────────────────────────────────────

describe('atmosphereRadius', () => {
  it('is strictly greater than base radius', () => {
    expect(atmosphereRadius(rocky({ radius: 1 }))).toBeGreaterThan(1)
  })

  it('scales proportionally with planet radius when palette is provided', () => {
    // With a fixed-height palette the formula is fully linear in r → ratio = 2.
    const palette = [{ threshold: Infinity, height: 0, color: {} as any }]
    const r1 = atmosphereRadius(rocky({ radius: 1, palette }))
    const r2 = atmosphereRadius(rocky({ radius: 2, palette }))
    expect(r2 / r1).toBeCloseTo(2, 5)
  })

  it('is always above terrain max height', () => {
    const maxH = 0.045
    const config = rocky({
      radius: 0.5,
      palette: [
        { threshold: 0.5, height: 0.01, color: {} as any },
        { threshold: 1.0, height: maxH,  color: {} as any },
      ],
    })
    expect(atmosphereRadius(config)).toBeGreaterThan(0.5 + maxH)
  })

  it('uses a safe fallback terrain height (0.06) when palette is absent', () => {
    // config.palette is null for dynamically generated planets — the fallback
    // must match the highest terrain generated by terrainPalette.ts (0.060).
    const noAtmo = atmosphereRadius(rocky({ radius: 1, palette: undefined }))
    const withFallback = atmosphereRadius(rocky({
      radius: 1,
      palette: [{ threshold: Infinity, height: 0.06, color: {} as any }],
    }))
    expect(noAtmo).toBeCloseTo(withFallback, 5)
  })

  it('has a visible gap (≥ 20 % of base radius) above the terrain top', () => {
    const maxH = 0.045
    const config = rocky({ radius: 1, palette: [{ threshold: Infinity, height: maxH, color: {} as any }] })
    const gap = atmosphereRadius(config) - (1 + maxH)
    expect(gap).toBeGreaterThan(0.19)   // ≥ 20 % of base radius (float-safe)
  })
})

// ── cloudCoverageFor ──────────────────────────────────────────────

describe('cloudCoverageFor', () => {
  it('returns null for non-rocky bodies', () => {
    expect(cloudCoverageFor({ ...rocky(), type: 'gaseous' })).toBeNull()
    expect(cloudCoverageFor({ ...rocky(), type: 'metallic' })).toBeNull()
    expect(cloudCoverageFor(star())).toBeNull()
  })

  it('returns null when atmosphere is too thin', () => {
    expect(cloudCoverageFor(rocky({ atmosphereThickness: 0.10, waterCoverage: 0.5 }))).toBeNull()
  })

  it('returns null when water coverage is too low', () => {
    expect(cloudCoverageFor(rocky({ atmosphereThickness: 0.5, waterCoverage: 0.05 }))).toBeNull()
  })

  it('returns null when planet is too cold for atmospheric water', () => {
    // canHaveAtmosphericWater requires avg temp > -60°C approximately
    expect(cloudCoverageFor(rocky({
      temperatureMin: -150,
      temperatureMax: -80,
      atmosphereThickness: 0.5,
      waterCoverage: 0.5,
    }))).toBeNull()
  })

  it('returns a coverage in (0, 0.75] for a temperate rocky planet', () => {
    const coverage = cloudCoverageFor(rocky({
      atmosphereThickness: 0.75,
      waterCoverage: 0.71,
    }))
    expect(coverage).not.toBeNull()
    expect(coverage!).toBeGreaterThan(0)
    expect(coverage!).toBeLessThanOrEqual(0.75)
  })

  it('caps coverage at 0.75', () => {
    const coverage = cloudCoverageFor(rocky({
      atmosphereThickness: 1.0,
      waterCoverage: 1.0,
    }))
    expect(coverage).not.toBeNull()
    expect(coverage!).toBeLessThanOrEqual(0.75)
  })
})

// ── hasAtmosphere ─────────────────────────────────────────────────

describe('hasAtmosphere', () => {
  it('always returns true for stars', () => {
    expect(hasAtmosphere(star())).toBe(true)
  })

  it('returns false when atmosphereThickness is below threshold', () => {
    expect(hasAtmosphere(rocky({ atmosphereThickness: 0.03 }))).toBe(false)
    expect(hasAtmosphere(rocky({ atmosphereThickness: undefined }))).toBe(false)
  })

  it('returns true when atmosphereThickness is at or above 0.05', () => {
    expect(hasAtmosphere(rocky({ atmosphereThickness: 0.05 }))).toBe(true)
    expect(hasAtmosphere(rocky({ atmosphereThickness: 0.75 }))).toBe(true)
  })
})

// ── auraParamsFor ─────────────────────────────────────────────────

describe('auraParamsFor', () => {
  it('returns a color string, intensity and power for a star', () => {
    const p = auraParamsFor(star())
    expect(p.color).toMatch(/^#[0-9a-f]{6}$/i)
    expect(p.intensity).toBeGreaterThan(0)
    expect(p.power).toBeGreaterThan(0)
  })

  it('gives blue color for a planet with liquid water', () => {
    const p = auraParamsFor(rocky({ waterCoverage: 0.71, atmosphereThickness: 0.75 }))
    expect(p.color).toBe('#2255ff')
  })

  it('gives olive color for an ammonia-liquid world', () => {
    // avg = -70, tempMax = -20 → ammonia liquid range, not frozen water
    const p = auraParamsFor(rocky({
      temperatureMin: -120,
      temperatureMax: -20,
      waterCoverage: 0.2,
      atmosphereThickness: 0.1,
    }))
    expect(p.color).toBe('#88aa33')
  })

  it('gives cyan color for a frozen world (no liquid)', () => {
    // avg = -155, tempMax = -130 → frozen water, no liquid of any kind
    const p = auraParamsFor(rocky({
      temperatureMin: -180,
      temperatureMax: -130,
      waterCoverage: 0.2,
      atmosphereThickness: 0.1,
    }))
    expect(p.color).toBe('#99ddff')
  })

  it('gives orange color for a hot/arid world', () => {
    const p = auraParamsFor(rocky({
      temperatureMin: 200,
      temperatureMax: 420,
      waterCoverage: 0,
      atmosphereThickness: 0.9,
    }))
    expect(p.color).toBe('#ff6622')
  })

  it('falls back to grey-blue for dry rocky planet', () => {
    const p = auraParamsFor(rocky({ waterCoverage: 0, atmosphereThickness: 0.18 }))
    expect(p.color).toBe('#7799bb')
  })

  it('star aura color is driven by spectral type, not temperature', () => {
    // spectralType takes priority — temperature alone would give wrong colour
    const mStar = auraParamsFor(star({ spectralType: 'M', temperatureMin: 20000, temperatureMax: 40000 }))
    const oStar = auraParamsFor(star({ spectralType: 'O', temperatureMin: 2000,  temperatureMax: 3000  }))
    expect(mStar.color).toBe('#ff2200')  // red, despite hot temperature
    expect(oStar.color).toBe('#aaddff')  // blue-white, despite cold temperature
  })

  it('star aura falls back to temperature when spectralType is absent', () => {
    const cold = auraParamsFor({ ...star(), spectralType: undefined, temperatureMin: 2000, temperatureMax: 3000 })
    const hot  = auraParamsFor({ ...star(), spectralType: undefined, temperatureMin: 20000, temperatureMax: 40000 })
    expect(cold.color).toBe('#ff2200')
    expect(hot.color).toBe('#aaddff')
  })
})
