import { describe, it, expect } from 'vitest'
import { auraParamsFor, atmosphereRadius, bodyOuterRadius, cloudShellRadius } from './sceneBodyUtils'
import type { BodyConfig } from '../types/body.types'

// ── Helpers ───────────────────────────────────────────────────────

function rocky(overrides: Partial<BodyConfig> = {}): BodyConfig {
  return {
    name: 'Test',
    type: 'rocky',
    temperatureMin: -10,
    temperatureMax: 30,
    radius: 1,
    rotationSpeed: 0.05,
    axialTilt: 0,
    ...overrides,
  }
}

function star(overrides: Partial<BodyConfig> = {}): BodyConfig {
  return {
    name: 'Sun',
    type: 'star',
    spectralType: 'G',
    temperatureMin: 5000,
    temperatureMax: 15000,
    radius: 3,
    rotationSpeed: 0.02,
    axialTilt: 0,
    ...overrides,
  }
}

// ── atmosphereRadius ──────────────────────────────────────────────

describe('atmosphereRadius', () => {
  it('is strictly greater than base radius', () => {
    expect(atmosphereRadius(rocky({ radius: 1 }))).toBeGreaterThan(1)
  })

  it('scales proportionally with planet radius when palette is provided', () => {
    // With a fixed-height palette the formula is fully linear in r → ratio = 2.
    const palette = [{ threshold: Infinity, height: 0, color: {} as any }]
    const r1 = atmosphereRadius(rocky({ radius: 1, palette }))
    const r2 = atmosphereRadius(rocky({ radius: 2, palette }))
    expect(r2 / r1).toBeCloseTo(2, 5)
  })

  it('is always above terrain max height', () => {
    const maxH = 0.045
    const config = rocky({
      radius: 0.5,
      palette: [
        { threshold: 0.5, height: 0.01, color: {} as any },
        { threshold: 1.0, height: maxH,  color: {} as any },
      ],
    })
    expect(atmosphereRadius(config)).toBeGreaterThan(0.5 + maxH)
  })

  it('uses a safe fallback terrain height (0.06) when palette is absent', () => {
    // config.palette is null for dynamically generated planets — the fallback
    // must match the highest terrain generated by terrainPalette.ts (0.060).
    const noAtmo = atmosphereRadius(rocky({ radius: 1, palette: undefined }))
    const withFallback = atmosphereRadius(rocky({
      radius: 1,
      palette: [{ threshold: Infinity, height: 0.06, color: {} as any }],
    }))
    expect(noAtmo).toBeCloseTo(withFallback, 5)
  })

  it('has a visible gap (≥ 20 % of base radius) above the terrain top', () => {
    const maxH = 0.045
    const config = rocky({ radius: 1, palette: [{ threshold: Infinity, height: maxH, color: {} as any }] })
    const gap = atmosphereRadius(config) - (1 + maxH)
    expect(gap).toBeGreaterThan(0.19)   // ≥ 20 % of base radius (float-safe)
  })
})

// ── bodyOuterRadius ───────────────────────────────────────────────

describe('bodyOuterRadius', () => {
  it('equals radius + palette max height when palette is provided', () => {
    const maxH = 0.045
    const config = rocky({
      radius: 1,
      palette: [
        { threshold: 0.5, height: 0.02, color: {} as any },
        { threshold: 1.0, height: maxH, color: {} as any },
      ],
    })
    expect(bodyOuterRadius(config)).toBeCloseTo(1 + maxH, 5)
  })

  it('uses the 0.06 fallback when palette is absent', () => {
    expect(bodyOuterRadius(rocky({ radius: 1 }))).toBeCloseTo(1.06, 5)
  })
})

// ── cloudShellRadius ──────────────────────────────────────────────

describe('cloudShellRadius', () => {
  it('clears the terrain top with an explicit gap (non-frozen)', () => {
    const maxH = 0.045
    const config = rocky({
      radius: 1,
      palette: [{ threshold: Infinity, height: maxH, color: {} as any }],
    })
    expect(cloudShellRadius(config, false)).toBeGreaterThan(1 + maxH)
  })

  it('frozen shell sits closer to the surface than the animated shell', () => {
    const config = rocky({ radius: 1 })
    expect(cloudShellRadius(config, true)).toBeLessThan(cloudShellRadius(config, false))
  })

  it('scales proportionally with planet radius when palette is flat', () => {
    const palette = [{ threshold: Infinity, height: 0, color: {} as any }]
    const r1 = cloudShellRadius(rocky({ radius: 1, palette }), false)
    const r2 = cloudShellRadius(rocky({ radius: 2, palette }), false)
    expect(r2 / r1).toBeCloseTo(2, 5)
  })

  it('stays below the atmosphere radius (clouds hug the planet)', () => {
    const config = rocky({ radius: 1 })
    expect(cloudShellRadius(config, false)).toBeLessThan(atmosphereRadius(config))
  })
})

// ── auraParamsFor ─────────────────────────────────────────────────

describe('auraParamsFor', () => {
  it('returns a color string, intensity and power for a star', () => {
    const p = auraParamsFor(star())
    expect(p.color).toMatch(/^#[0-9a-f]{6}$/i)
    expect(p.intensity).toBeGreaterThan(0)
    expect(p.power).toBeGreaterThan(0)
  })

  it('gives blue color for a planet with liquid water', () => {
    const p = auraParamsFor(rocky({
      liquidCoverage: 0.71, liquidType: 'water', liquidState: 'liquid',
      atmosphereThickness: 0.75,
    }))
    expect(p.color).toBe('#2255ff')
  })

  it('gives olive color for an ammonia-liquid world', () => {
    const p = auraParamsFor(rocky({
      temperatureMin: -120,
      temperatureMax: -20,
      liquidCoverage: 0.2, liquidType: 'ammonia', liquidState: 'liquid',
      atmosphereThickness: 0.1,
    }))
    expect(p.color).toBe('#88aa33')
  })

  it('falls back to blue for an unknown liquid tag', () => {
    const p = auraParamsFor(rocky({
      liquidCoverage: 0.4, liquidType: 'plasma-soup', liquidState: 'liquid',
      atmosphereThickness: 0.3,
    }))
    expect(p.color).toBe('#2255ff')
  })

  it('gives cyan color for a frozen world (no liquid flow)', () => {
    const p = auraParamsFor(rocky({
      temperatureMin: -180,
      temperatureMax: -130,
      liquidCoverage: 0.2, liquidType: 'water', liquidState: 'frozen',
      atmosphereThickness: 0.1,
    }))
    expect(p.color).toBe('#99ddff')
  })

  it('gives orange color for a hot/arid world', () => {
    const p = auraParamsFor(rocky({
      temperatureMin: 200,
      temperatureMax: 420,
      liquidCoverage: 0,
      atmosphereThickness: 0.9,
    }))
    expect(p.color).toBe('#ff6622')
  })

  it('falls back to grey-blue for dry rocky planet', () => {
    const p = auraParamsFor(rocky({ liquidCoverage: 0, atmosphereThickness: 0.18 }))
    expect(p.color).toBe('#7799bb')
  })

  it('star aura color is driven by spectral type, not temperature', () => {
    // spectralType takes priority — temperature alone would give wrong colour
    const mStar = auraParamsFor(star({ spectralType: 'M', temperatureMin: 20000, temperatureMax: 40000 }))
    const oStar = auraParamsFor(star({ spectralType: 'O', temperatureMin: 2000,  temperatureMax: 3000  }))
    expect(mStar.color).toBe('#ff2200')  // red, despite hot temperature
    expect(oStar.color).toBe('#aaddff')  // blue-white, despite cold temperature
  })

  it('star aura falls back to temperature when spectralType is absent', () => {
    const cold = auraParamsFor({ ...star(), spectralType: undefined, temperatureMin: 2000, temperatureMax: 3000 })
    const hot  = auraParamsFor({ ...star(), spectralType: undefined, temperatureMin: 20000, temperatureMax: 40000 })
    expect(cold.color).toBe('#ff2200')
    expect(hot.color).toBe('#aaddff')
  })
})
