/**
 * Unified atmosphere shader.
 *
 * One shader, two render variants resolved at build time from the requested
 * `opacity`:
 *
 *  - **opaque**     (`opacity ≥ 0.99`) — solid colour shell, depth-write on,
 *    lambertian shading. Used by:
 *      * the **interactive `'atmosphere'` view** — playable atmo board where
 *        per-tile resources are read off as flat colours, no see-through.
 *      * the **`'shader'` view on gas giants** — opaque envelope means the
 *        smooth sphere underneath can be skipped entirely.
 *  - **translucent** (`opacity < 0.99`) — halo with rim fresnel + vertical
 *    gradient, depth-write off, alpha-blended. Used by the **`'shader'`
 *    view on rocky bodies**, where the smooth sphere reads through the
 *    halo.
 *
 * Per-tile resource colours flow through `applyTileOverlay('atmo', …)` and
 * are read by both variants via the `vTileColor` varying — gameplay drives
 * the visual, no procedural band pattern is generated by this shader.
 */

import * as THREE from 'three'
import type { BodyConfig } from '../../types/body.types'
import type { BodyVariation } from '../body/bodyVariation'
import { resolveCoreRadiusRatio } from '../../physics/body'

/**
 * Neutral default tint when the caller doesn't push one. Pale sky-blue —
 * reads as "atmospheric" without committing to a thermal class. Callers
 * that want a climate-driven hue derive it caller-side and pass it via
 * {@link AtmoMaterialOptions.tint}.
 */
const DEFAULT_ATMO_TINT = '#aaccff'

/** Render variant resolved at build time from {@link AtmoMaterialOptions.opacity}. */
export type AtmoMaterialMode = 'opaque' | 'translucent'

/** Threshold above which {@link AtmoMaterialOptions.opacity} produces an opaque shell. */
const OPAQUE_THRESHOLD = 0.99

/** Options forwarded to the underlying `THREE.ShaderMaterial`. */
export interface AtmoMaterialOptions {
  /**
   * Atmosphere opacity in `[0, 1]`. Selects the render variant:
   *   - `≥ 0.99` → opaque shell, no fresnel / gradient
   *   - `< 0.99` → translucent halo, alpha = opacity × fresnel × gradient
   * Defaults to `1` (fully opaque — interactive playable atmo).
   */
  opacity?:      number
  /** Override the temperature-derived tint. Hex string (`#rrggbb`). */
  tint?:         string
  /** Initial light direction in world space. Defaults to `[1, 0.5, 1]`. */
  lightDir?:     [number, number, number]
  /** Fresnel falloff exponent (translucent only). Higher → thinner rim. Defaults to `2.5`. */
  fresnelPower?: number
}

/** Handle returned by {@link createAtmoMaterial}. */
export interface AtmoMaterialHandle {
  /** Resolved render variant. */
  mode:     AtmoMaterialMode
  /** Ready-to-assign `THREE.ShaderMaterial`. */
  material: THREE.ShaderMaterial
  /** Updates the `uTime` uniform (reserved for animated tints / noise). */
  tick: (elapsed: number) => void
  /** Mutates the light direction in place, no material rebuild. */
  setLight: (opts: { direction?: THREE.Vector3 | [number, number, number] }) => void
  /** Live-update of scalar params. Mutating opacity does NOT switch variants. */
  setParams: (partial: { opacity?: number; fresnelPower?: number }) => void
  /** Disposes the underlying material. Idempotent. */
  dispose: () => void
}

function resolveDir(input: THREE.Vector3 | [number, number, number]): THREE.Vector3 {
  if (input instanceof THREE.Vector3) return input.clone().normalize()
  return new THREE.Vector3(input[0], input[1], input[2]).normalize()
}

const VERTEX_SHADER = /* glsl */ `
  attribute float aLayer;
  attribute float aSolHeight;
  // Per-tile overlay tint, stamped by \`InteractiveMesh.applyTileOverlay('atmo', …)\`.
  // Empty ((0,0,0)) until the caller paints a tile — the shader then falls back
  // to the uniform tint. Three.js binds this attribute automatically because
  // the overlay API writes a \`color\` BufferAttribute.
  attribute vec3  color;
  varying vec3  vWorldPos;
  varying vec3  vWorldNormal;
  varying float vSolHeight;
  varying vec3  vTileColor;

  void main() {
    vec4 wp       = modelMatrix * vec4(position, 1.0);
    vWorldPos     = wp.xyz;
    vWorldNormal  = normalize(mat3(modelMatrix) * normal);
    vSolHeight    = aSolHeight;
    vTileColor    = color;
    gl_Position   = projectionMatrix * viewMatrix * wp;
  }
`

const FRAGMENT_SHADER_OPAQUE = /* glsl */ `
  uniform vec3 uTint;
  uniform vec3 uLightDir;

  varying vec3 vWorldPos;
  varying vec3 vWorldNormal;
  varying vec3 vTileColor;

  void main() {
    vec3 N = normalize(vWorldNormal);

    // Per-tile overlay — when the caller paints a tile via
    // \`applyTileOverlay('atmo', …)\` we use that tint, otherwise we fall back
    // to the body-level temperature tint so an unpainted opaque atmo still
    // reads as a coherent shell.
    float tileMask = step(0.005, max(max(vTileColor.r, vTileColor.g), vTileColor.b));
    vec3  baseTint = mix(uTint, vTileColor, tileMask);

    // Soft lambertian — ambient floor keeps the dark side readable.
    float diff = 0.35 + 0.65 * max(dot(N, normalize(uLightDir)), 0.0);

    gl_FragColor = vec4(baseTint * diff, 1.0);
  }
`

const FRAGMENT_SHADER_TRANSLUCENT = /* glsl */ `
  uniform vec3  uTint;
  uniform vec3  uLightDir;
  uniform float uOpacity;
  uniform float uFresnelPower;
  uniform float uCoreRadius;
  uniform float uTotalThickness;

  varying vec3  vWorldPos;
  varying vec3  vWorldNormal;
  varying float vSolHeight;
  varying vec3  vTileColor;

  void main() {
    vec3 N = normalize(vWorldNormal);
    vec3 V = normalize(cameraPosition - vWorldPos);
    vec3 R = normalize(vWorldPos); // radial direction — world-space outward normal

    // Prism walls (normal tangential to the shell) would render as bright
    // radial spokes since they span the entire atmo band and face the camera
    // at grazing angles. We drop them entirely — only top caps (normal
    // radially outward) contribute to the halo.
    if (abs(dot(N, R)) < 0.8) discard;

    // Rim falloff — strongest at grazing angles, near zero at the centre.
    float fres = pow(1.0 - clamp(dot(N, V), 0.0, 1.0), uFresnelPower);

    // Vertical gradient along the atmo band. \`r\` is the current vertex's
    // distance to the origin; the band spans [coreRadius + solH, surface].
    float r        = length(vWorldPos);
    float atmoSpan = max(1e-4, uTotalThickness - vSolHeight);
    float t        = clamp((r - (uCoreRadius + vSolHeight)) / atmoSpan, 0.0, 1.0);
    float gradient = smoothstep(0.0, 0.6, t);

    // Soft lambertian — ambient floor keeps the dark side readable.
    float diff = 0.35 + 0.65 * max(dot(N, normalize(uLightDir)), 0.0);

    float alpha = uOpacity * fres * gradient;
    if (alpha <= 0.001) discard;

    // Per-tile overlay — see opaque shader for rationale.
    float tileMask = step(0.005, max(max(vTileColor.r, vTileColor.g), vTileColor.b));
    vec3  baseTint = mix(uTint, vTileColor, tileMask);

    gl_FragColor = vec4(baseTint * diff, alpha);
  }
`

/**
 * Builds the atmosphere material for a non-stellar body.
 *
 * The returned material is meant to be assigned to the **atmo group** of the
 * layered interactive mesh (material index 1). It reads `aLayer` and
 * `aSolHeight` attributes emitted by `buildLayeredPrismGeometry`.
 *
 * @param config    - Body configuration — drives tint and shell metrics.
 * @param variation - Deterministic visual variation. Reserved for future
 *                    detail noise; currently unused.
 * @param options   - Opacity selector + overrides for tint, light, fresnel.
 */
export function createAtmoMaterial(
  config:     BodyConfig,
  variation?: BodyVariation,
  options:    AtmoMaterialOptions = {},
): AtmoMaterialHandle {
  void variation // reserved for future detail noise

  const opacity     = Math.max(0, Math.min(1, options.opacity ?? 1))
  const mode: AtmoMaterialMode = opacity >= OPAQUE_THRESHOLD ? 'opaque' : 'translucent'

  const tintHex     = options.tint ?? DEFAULT_ATMO_TINT
  const tintColor   = new THREE.Color(tintHex)
  const surfaceRadius  = config.radius
  const coreRadius     = surfaceRadius * resolveCoreRadiusRatio(config)
  const totalThickness = surfaceRadius - coreRadius

  const lightDir = resolveDir(options.lightDir ?? [1, 0.5, 1])

  if (mode === 'opaque') {
    const uniforms: Record<string, THREE.IUniform> = {
      uTint:     { value: new THREE.Vector3(tintColor.r, tintColor.g, tintColor.b) },
      uLightDir: { value: lightDir },
      uTime:     { value: 0 },
    }

    const material = new THREE.ShaderMaterial({
      uniforms,
      vertexShader:   VERTEX_SHADER,
      fragmentShader: FRAGMENT_SHADER_OPAQUE,
      transparent:    false,
      depthWrite:     true,
      side:           THREE.FrontSide,
    })

    return {
      mode,
      material,
      tick(elapsed) { uniforms.uTime.value = elapsed },
      setLight({ direction }) {
        if (direction !== undefined) {
          (uniforms.uLightDir.value as THREE.Vector3).copy(resolveDir(direction))
        }
      },
      // Opacity / fresnel are no-ops on the opaque variant — kept for API parity.
      setParams() { /* noop */ },
      dispose() { material.dispose() },
    }
  }

  // ── translucent variant ─────────────────────────────────────────
  const uniforms: Record<string, THREE.IUniform> = {
    uTint:           { value: new THREE.Vector3(tintColor.r, tintColor.g, tintColor.b) },
    uLightDir:       { value: lightDir },
    uOpacity:        { value: opacity },
    uFresnelPower:   { value: options.fresnelPower ?? 2.5 },
    uCoreRadius:     { value: coreRadius },
    uTotalThickness: { value: totalThickness },
    uTime:           { value: 0 },
  }

  const material = new THREE.ShaderMaterial({
    uniforms,
    vertexShader:   VERTEX_SHADER,
    fragmentShader: FRAGMENT_SHADER_TRANSLUCENT,
    transparent:    true,
    depthWrite:     false,
    side:           THREE.FrontSide,
    blending:       THREE.NormalBlending,
  })
  material.visible = uniforms.uOpacity.value > 0

  return {
    mode,
    material,
    tick(elapsed) { uniforms.uTime.value = elapsed },
    setLight({ direction }) {
      if (direction !== undefined) {
        (uniforms.uLightDir.value as THREE.Vector3).copy(resolveDir(direction))
      }
    },
    setParams({ opacity: o, fresnelPower }) {
      if (o !== undefined) {
        uniforms.uOpacity.value = o
        material.visible        = o > 0
      }
      if (fresnelPower !== undefined) {
        uniforms.uFresnelPower.value = fresnelPower
      }
    },
    dispose() { material.dispose() },
  }
}
